version: 2.1

orbs:
  heroku: circleci/heroku@0.0.5

defaults: &defaults
  working_directory: /home/circleci/project
  docker:
    - image: circleci/node:10

save_code: &save_code
  save_cache:
    key: code-{{ .Revision }}
    paths:
      - .git

save_dep: &save_dep
  save_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

restore_code: &restore_code
  restore_cache:
    key: code-{{ .Revision }}

restore_dep: &restore_dep
  restore_cache:
    key: dependency-cache-{{ checksum "yarn.lock" }}

jobs:
  build:
    working_directory: /home/circleci/project
    machine: true
    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep

      - run:
          name: "Install solc binary"
          command: |
            sudo apt update
            sudo apt install snapd
            sudo snap install solc

      - run:
          name: "Install nvm, node 10 and yarn"
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v10
            nvm alias default v10
            # Each step uses the same `$BASH_ENV`, so need to modify it
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
            curl -o- -L https://yarnpkg.com/install.sh | bash

      - run:
          name: "Running yarn build"
          command: |
            ~/.yarn/bin/yarn --frozen-lockfile
            ~/.yarn/bin/yarn  build

      - <<: *save_dep
      - <<: *save_code

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packages/*/dist
            - packages/*/build

  run-tests:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep

      - run: yarn --frozen-lockfile # symlink packages' node_modules

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Run Non-Playground-related tests
          command: yarn test:ci-non-playground

  run-playground-tests:
    <<: *defaults
    docker:
      - image: circleci/node:10-browsers
    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep

      - run: yarn --frozen-lockfile # symlink packages' node_modules

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Run Playground tests
          command: cd packages/playground && yarn test
      - run:
          name: Run Playground Server tests
          command: cd packages/playground-server && yarn test:ci
      - run:
          name: Run High Roller tests
          command: cd packages/dapp-high-roller && yarn test
      - run:
          name: Run Tic-Tac-Toe tests
          command: cd packages/dapp-tic-tac-toe && yarn test

  run-tslint:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep

      - attach_workspace:
          at: /home/circleci/project

      - run: yarn lint

  publish-to-npm:
    <<: *defaults
    steps:
      - <<: *restore_code
      - checkout
      - <<: *restore_dep

      - run: yarn --frozen-lockfile # symlink packages' node_modules

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Add NPM_TOKEN auth
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

      - run:
          name: Publish any updated packages to npm
          command: yarn run publish

workflows:
  run-tests:
    jobs:
      - build

      - run-tslint:
          requires:
            - build

      - run-tests:
          requires:
            - build

      - run-playground-tests:
          requires:
            - build

      - publish-to-npm:
          requires:
            - build
            - run-tests
            - run-playground-tests
            - run-tslint
          filters:
            branches:
              only: master

      - heroku/deploy-via-git:
          app-name: playground-server-staging
          requires:
            - publish-to-npm
          filters:
            branches:
              only: master

      - heroku/deploy-via-git:
          app-name: hr-bot-staging
          requires:
            - publish-to-npm
          filters:
            branches:
              only: master

      - heroku/deploy-via-git:
          app-name: ttt-bot-staging
          requires:
            - publish-to-npm
          filters:
            branches:
              only: master


